"! @testing /DMO/CL_I_TRAVEL_TUM
"! @testing /DMO/CL_C_TRAVEL_TUM
"! @testing /DMO/CL_FLIGHT_LEGACY17
"! @testing FUGR:/DMO/FLIGHT_TRAVEL_API17
CLASS ltc DEFINITION FINAL INHERITING FROM /dmo/tc_flight_travel_api17 FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM.
ENDCLASS.
